### PR TITLE
#164046240 Integrating Code Climate to Authors Haven

### PR DESCRIPTION
**Pull request by Etomovich**
**What does this PR do?**
This PR configures Code Climate and adds maintainability badge to the README.md

**Description of task to be completed?**
- configure Code Climate
- add maintainability badges to README.md

**How should	this be manually tested?**
- [Maintainability](https://codeclimate.com/github/andela/ah-legion-backend/badges#maintainability-markdown)

**Any background context you may want to provide?**
- code climate helps our team ship better code, faster, by incorporating fully-configurable static analysis and test coverage data into your development workflow.

**What are the relevant pivotal tracer stories?**
- [#164046240](https://www.pivotaltracker.com/story/show/164046240)

### CODE REVIEW

**Review by MandelaK — APPROVED** [review]
Looks good to me

**Review by ElMonstro — APPROVED** [review]
Approved

**Review by RachelleMaina — APPROVED** [review]

**Review by cob04 — APPROVED** [review]
the badge works great

**Review by MandelaK — APPROVED** [review]
LGTM

**Review by BrianSerem — APPROVED** [review]

**Pull request merged**
