### PR TITLE
chore(pep8): implement pep8 standards on codebase

### PR DESCRIPTION
**Pull request by ElMonstro**
#### What does this PR do?
Adds testing of code for PEP8 style guide compliance
#### Description of Task to be completed?
- Add PEP8 checking packages
- Add PEP8 testing script to travis.yml
#### How should this be manually tested?
* Clone this repo `git clone https://github.com/andela/ah-legion-backend.git`
* Install dependencies with the command `pip install -r requirements.txt` from the root folder.
* git checkout origin/ch-implement-pep8-164243636
* Run `find ./authors/ -name \*.py -exec flake8 -v {} +`
- VIew travis [build](https://travis-ci.com/andela/ah-legion-backend/builds/102683228)
#### Any background context you want to provide?
PEP8 styled code is highly readable and easier to maintain
#### What are the relevant pivotal tracker stories?
[#164243636](https://www.pivotaltracker.com/story/show/164243636)

### CODE REVIEW

**Comment by MandelaK** [comment]
@ElMonstro I have run `find ./authors/ -name \*.py -exec flake8 {} +` but I don't see any change or information. What do I expect to happen after running the command?

**Comment by ElMonstro** [comment]
> @ElMonstro I have run `find ./authors/ -name \*.py -exec flake8 {} +` but I don't see any change or information. What do I expect to happen after running the command?

It will list all PEP8 violations if present in the code base and exit with 1 hence failing the build which is the story requirement. I can insert a verbose flag in the flag to output more information.

**Comment by MandelaK** [comment]
@ElMonstro When I run the command I get absolutely no output, does this mean it found no errors?

**Review by MandelaK — APPROVED** [review]
Thanks for the verbose flag, everything looks ok

**Review by cob04 — APPROVED** [review]
looks good, no PEP8 violations

**Review by Etomovich — APPROVED** [review]
LGTM

**Review by RachelleMaina — APPROVED** [review]

**Review by BrianSerem — APPROVED** [review]
All tests are passing, solve the conflict in travis.yml

**Review by RachelleMaina — APPROVED** [review]

**Pull request closed without merging**
